version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 9112
    ports:
      - 9112:9112/tcp
      - 9112:9112/udp
  validator:
    build:
      args:
        NETWORK: mainnet
