version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: gnosis
        P2P_PORT: 19012
    ports:
      - 19012:19012/tcp
      - 19012:19012/udp
  validator:
    build:
      args:
        NETWORK: gnosis
