version: "3.5"
services:
  beacon-chain:
    image: beacon-chain.lodestar-gnosis.dnp.dappnode.eth:0.1.13
    build:
      args:
        NETWORK: gnosis
    ports:
      - 9612:9612/tcp
      - 9612:9612/udp
  validator:
    image: validator.lodestar-gnosis.dnp.dappnode.eth:0.1.13
    build:
      args:
        NETWORK: gnosis
