version: "3.5"
services:
  beacon-chain:
    build:
      args:
        NETWORK: holesky
        P2P_PORT: 9612
    ports:
      - 9612:9612/tcp
      - 9612:9612/udp
  validator:
    build:
      args:
        NETWORK: holesky
