version: "3.5"
services:
  beacon-chain:
    image: beacon-chain.lodestar-holesky.dnp.dappnode.eth:0.1.5
    build:
      args:
        NETWORK: holesky
        P2P_PORT: 9612
    ports:
      - 9612:9612/tcp
      - 9612:9612/udp
  validator:
    image: validator.lodestar-holesky.dnp.dappnode.eth:0.1.5
    build:
      args:
        NETWORK: holesky
