name: Bump upstream version

on:
  schedule:
    - cron: "00 */4 * * *"
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.TROPI_APP_ID }}
          private-key: ${{ secrets.TROPI_APP_PRIVATE_KEY }}
      - run: npx @dappnode/dappnodesdk github-action bump-upstream --use_variants
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
